# Build Maverick on python 3.5+

name: Build Py39

on:
  push:
    branches:
      - master

jobs:

  build_py35:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        make dep

    - name: Build
      run: |
        make site
